[project]
name = "pyhanko-pdf-signer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=44.0.2",
    "PyQt5==5.15.11",
    "PyQt5-sip==12.17.0"
]
